return {
    'nvim-treesitter/nvim-treesitter',
    commit = '94ea4f4',
    config = function()
        require('nvim-treesitter.configs').setup({
            -- Add languages to be installed here that you want installed for treesitter
            ensure_installed = {
                'asm',
                'bash',
                'c',
                'c_sharp',
                'cmake',
                'cpp',
                'css',
                'dart',
                'diff',
                'dockerfile',
                'editorconfig',
                'git_rebase',
                'gitcommit',
                'gitignore',
                'go',
                'gomod',
                'gowork',
                'graphql',
                'groovy',
                'hcl',
                'html',
                'http',
                'java',
                'javadoc',
                'javascript',
                'jsdoc',
                'json',
                'json5',
                'jsonc',
                'kotlin',
                'lua',
                'luadoc',
                'make',
                'markdown',
                'markdown_inline',
                'mermaid',
                'ninja',
                'passwd',
                'php',
                'prisma',
                'properties',
                'proto',
                'python',
                'query',
                'regex',
                'robots',
                'ruby',
                'rust',
                'smali',
                'scss',
                'sql',
                'ssh_config',
                'swift',
                'terraform',
                'tmux',
                'toml',
                'tsx',
                'typescript',
                'vim',
                'vimdoc',
                'vue',
                'xml',
                'yaml'
            },
            auto_install = true,
            highlight = {
                enable = true,
                additional_vim_regex_highlighting = false,
            },
            indent = {
                enable = true,
            },
        })
    end
}
