local treesitter_config = require 'nvim-treesitter.configs'

treesitter_config.setup({
    -- Add languages to be installed here that you want installed for treesitter
    ensure_installed = {
        'bash',
        'c',
        'cmake',
        'cpp',
        'c_sharp',
        'css',
        'dockerfile',
        'go',
        'gomod',
        'gowork',
        'graphql',
        'html',
        'java',
        'javascript',
        'jsdoc',
        'json',
        'json5',
        'jsonc',
        'kotlin',
        'lua',
        'luadoc',
        'make',
        'markdown',
        'mermaid',
        'prisma',
        'proto',
        'python',
        'query',
        'regex',
        'ruby',
        'rust',
        'scss',
        'sql',
        'swift',
        'toml',
        'tsx',
        'typescript',
        'vim',
        'vimdoc',
        'yaml'
    },
    auto_install = true,
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = { 'ruby' },
    },
    indent = {
        enable = true,
        disable = { 'ruby' },
    },
})
